#ifndef OBJECTGRAPHVIEW_GLOBAL_H
#define OBJECTGRAPHVIEW_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(OBJECTGRAPHVIEW_LIBRARY)
#  define OBJECTGRAPHVIEWSHARED_EXPORT Q_DECL_EXPORT
#else
#  define OBJECTGRAPHVIEWSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // OBJECTGRAPHVIEW_GLOBAL_H
