#ifndef OBJECTGRAPHUTIL_GLOBAL_H
#define OBJECTGRAPHUTIL_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(OBJECTGRAPHUTIL_LIBRARY)
#  define OBJECTGRAPHUTILSHARED_EXPORT Q_DECL_EXPORT
#else
#  define OBJECTGRAPHUTILSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // OBJECTGRAPHUTIL_GLOBAL_H
