#ifndef OBJECTGRAPH_GLOBAL_H
#define OBJECTGRAPH_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(OBJECTGRAPH_LIBRARY)
#  define OBJECTGRAPHSHARED_EXPORT Q_DECL_EXPORT
#else
#  define OBJECTGRAPHSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // OBJECTGRAPH_GLOBAL_H
